""" file:   __init__.py (pysiss)
    author: Jess Robertson
            CSIRO Minerals Resources Flagship
    date:   Monday 28 July 2014

    description: Init file for pysiss
"""

from . import borehole, geospatial, utilities, webservices, metadata
from .metadata import Metadata
from .geospatial import Coverage, Feature
from .borehole import Borehole

# Load git autogenerated version - update with setup.py update_version
from ._version import __version__

__all__ = ['borehole', 'geospatial', 'utilities', 'webservices', 'metadata',
           'Metadata', 'Borehole', 'Coverage', 'Feature',
           '__version__']

# Set logging config
import logging.config
from ._log_config import LOG_CONFIG
logging.config.dictConfig(LOG_CONFIG)
